--In this folder are all 4 costumes you requested
--The names are there so I could find them and you can change them whenever you like
--In the script I used there are the costume triggers which grab a context
--I have added in the costume contexts so you can change these costumes to your liking
--I hope you like these and that the players do as well